// ============================================================
// TestMind Phase 1 — Selenium Java Code Generator
// Pure deterministic codegen — no AI, no external calls
// ============================================================

interface CodeGenOptions {
  framework?:       'testng' | 'junit5' | 'junit4';
  waitSec?:         number;
  driverType?:      string;
  addComments?:     boolean;
}

interface CodeGenMeta {
  className:   string;
  packageName: string;
  baseUrl:     string;
}

export class CodeGen {
  private fw      : string;
  private waitSec : number;
  private driver  : string;
  private comments: boolean;

  constructor(opts: CodeGenOptions = {}) {
    this.fw       = opts.framework   || 'testng';
    this.waitSec  = opts.waitSec     ?? 10;
    this.driver   = opts.driverType  || 'ChromeDriver';
    this.comments = opts.addComments !== false;
  }

  generate(events: any[], meta: CodeGenMeta): string {
    const lines: string[] = [
      `package ${meta.packageName};`,
      '',
      ...this._imports(),
      '',
      ...this._class(events, meta.className, meta.baseUrl),
    ];
    return lines.join('\n');
  }

  // ── Imports ───────────────────────────────────────────────
  private _imports(): string[] {
    const base = [
      'import org.openqa.selenium.By;',
      'import org.openqa.selenium.Keys;',
      'import org.openqa.selenium.WebDriver;',
      'import org.openqa.selenium.WebElement;',
      'import org.openqa.selenium.chrome.ChromeDriver;',
      'import org.openqa.selenium.chrome.ChromeOptions;',
      'import org.openqa.selenium.interactions.Actions;',
      'import org.openqa.selenium.JavascriptExecutor;',
      'import org.openqa.selenium.support.ui.ExpectedConditions;',
      'import org.openqa.selenium.support.ui.Select;',
      'import org.openqa.selenium.support.ui.WebDriverWait;',
      'import java.time.Duration;',
    ];

    if (this.fw === 'testng') return [
      ...base,
      'import org.testng.Assert;',
      'import org.testng.annotations.AfterMethod;',
      'import org.testng.annotations.BeforeMethod;',
      'import org.testng.annotations.Test;',
    ];

    if (this.fw === 'junit5') return [
      ...base,
      'import org.junit.jupiter.api.AfterEach;',
      'import org.junit.jupiter.api.BeforeEach;',
      'import org.junit.jupiter.api.Test;',
      'import static org.junit.jupiter.api.Assertions.*;',
    ];

    // junit4
    return [
      ...base,
      'import org.junit.After;',
      'import org.junit.Before;',
      'import org.junit.Test;',
      'import static org.junit.Assert.*;',
    ];
  }

  // ── Class wrapper ─────────────────────────────────────────
  private _class(events: any[], cls: string, baseUrl: string): string[] {
    const bef = this.fw === 'testng' ? '@BeforeMethod' : this.fw === 'junit5' ? '@BeforeEach' : '@Before';
    const aft = this.fw === 'testng' ? '@AfterMethod'  : this.fw === 'junit5' ? '@AfterEach'  : '@After';
    const w   = this.waitSec;

    return [
      '/**',
      ' * Generated by TestMind VSCode Extension — Phase 1',
      ` * Base URL  : ${baseUrl || 'N/A'}`,
      ` * Steps     : ${events.length}`,
      ` * Framework : ${this.fw.toUpperCase()}`,
      ` * Generated : ${new Date().toISOString()}`,
      ' *',
      ' * ⚠  Replace ***MASKED*** passwords before committing.',
      ' */',
      `public class ${cls} {`,
      '',
      '    private WebDriver driver;',
      '    private WebDriverWait wait;',
      '    private Actions actions;',
      '',
      `    ${bef}`,
      '    public void setUp() {',
      '        // WebDriverManager.chromedriver().setup(); // add io.github.bonigarcia:webdrivermanager',
      '        ChromeOptions options = new ChromeOptions();',
      '        options.addArguments("--start-maximized");',
      `        driver  = new ${this.driver}(options);`,
      `        wait    = new WebDriverWait(driver, Duration.ofSeconds(${w}));`,
      '        actions = new Actions(driver);',
      '    }',
      '',
      `    ${aft}`,
      '    public void tearDown() {',
      '        if (driver != null) { driver.quit(); }',
      '    }',
      '',
      '    @Test',
      '    public void recordedTest() {',
      ...this._body(events),
      '    }',
      '',
      '    // ─── Helpers ──────────────────────────────────────────',
      '    private void waitForPageLoad() {',
      '        wait.until(driver ->',
      '            ((JavascriptExecutor) driver)',
      '                .executeScript("return document.readyState").equals("complete"));',
      '    }',
      '',
      '    private void scrollIntoView(WebElement el) {',
      '        ((JavascriptExecutor) driver)',
      '            .executeScript("arguments[0].scrollIntoView({behavior:\'smooth\',block:\'center\'});", el);',
      '    }',
      '',
      '    private void safeClick(By locator) {',
      '        for (int i = 0; i < 3; i++) {',
      '            try {',
      '                wait.until(ExpectedConditions.elementToBeClickable(locator)).click();',
      '                return;',
      '            } catch (org.openqa.selenium.StaleElementReferenceException ignored) {}',
      '        }',
      '    }',
      '}',
    ];
  }

  // ── Test body ─────────────────────────────────────────────
  private _body(events: any[]): string[] {
    const lines: string[] = [];

    events.forEach((evt, i) => {
      const stmts = this._stmt(evt, i);
      if (!stmts) return;

      // Comment with element description when available
      if (this.comments) {
        const desc = this._describe(evt);
        if (desc) lines.push(`        // ${desc}`);
      }

      stmts.forEach(s => lines.push(`        ${s}`));
      lines.push('');
    });

    return lines;
  }

  // ── Event → Java statement(s) ─────────────────────────────
  private _stmt(evt: any, idx: number): string[] | null {
    const by = this._by(evt.selectors);

    switch (evt.type) {

      case 'navigate':
        return [
          `driver.get("${this._esc(evt.url)}");`,
          `waitForPageLoad();`,
        ];

      case 'click':
        return [`wait.until(ExpectedConditions.elementToBeClickable(${by})).click();`];

      case 'doubleClick':
        return [
          `WebElement el${idx} = wait.until(ExpectedConditions.visibilityOfElementLocated(${by}));`,
          `actions.doubleClick(el${idx}).perform();`,
        ];

      case 'input': {
        const val = this._esc(evt.value || '');
        return [
          `WebElement input${idx} = wait.until(ExpectedConditions.visibilityOfElementLocated(${by}));`,
          `input${idx}.clear();`,
          `input${idx}.sendKeys("${val}");`,
        ];
      }

      case 'select':
        return [
          `Select sel${idx} = new Select(wait.until(ExpectedConditions.visibilityOfElementLocated(${by})));`,
          `sel${idx}.selectByVisibleText("${this._esc(evt.selectedText || evt.value || '')}");`,
        ];

      case 'check':
        return [
          `WebElement cb${idx} = wait.until(ExpectedConditions.elementToBeClickable(${by}));`,
          `if (cb${idx}.isSelected() != ${!!evt.checked}) { cb${idx}.click(); }`,
        ];

      case 'radio':
        return [`wait.until(ExpectedConditions.elementToBeClickable(${by})).click();`];

      case 'keyPress': {
        const keyMap: Record<string, string> = {
          Enter:     'Keys.ENTER',
          Tab:       'Keys.TAB',
          Escape:    'Keys.ESCAPE',
          ArrowUp:   'Keys.ARROW_UP',
          ArrowDown: 'Keys.ARROW_DOWN',
          ArrowLeft: 'Keys.ARROW_LEFT',
          ArrowRight:'Keys.ARROW_RIGHT',
          Backspace: 'Keys.BACK_SPACE',
          Delete:    'Keys.DELETE',
          F5:        'Keys.F5',
          F12:       'Keys.F12',
        };
        const k = keyMap[evt.key];
        if (!k) return null;
        return [`driver.findElement(${by}).sendKeys(${k});`];
      }

      case 'scroll':
        return [
          `((JavascriptExecutor) driver).executeScript(` +
          `"window.scrollTo(${evt.scrollX || 0}, ${evt.scrollY || 0});");`,
        ];

      case 'formSubmit':
        return [
          `driver.findElement(${by}).submit();`,
          `waitForPageLoad();`,
        ];

      default:
        return null;
    }
  }

  // ── Selector → By.xxx ─────────────────────────────────────
  private _by(selectors: any): string {
    const best = selectors?.best;
    if (!best?.value) return `By.cssSelector("/* TODO: add selector */")`;

    switch (best.type) {
      case 'id':
        // Strip leading '#'
        return `By.id("${this._esc(best.value.replace(/^#/, ''))}")`;
      case 'name':
        // Extract name value from [name="..."]
        return `By.name("${this._esc(best.value.match(/\[name="(.+?)"\]/)?.[1] || best.value)}")`;
      case 'linkText':
        return `By.linkText("${this._esc(best.value)}")`;
      case 'xpath':
        return `By.xpath("${this._esc(best.value)}")`;
      default:
        // testId, ariaLabel, placeholder, css all become cssSelector
        return `By.cssSelector("${this._esc(best.value)}")`;
    }
  }

  // ── Utilities ─────────────────────────────────────────────
  private _describe(evt: any): string {
    const info = evt.elementInfo || {};
    switch (evt.type) {
      case 'navigate':    return `Navigate → ${evt.url?.slice(0, 60)}`;
      case 'click':       return `Click: ${info.innerText?.slice(0, 40) || info.tagName || ''}`;
      case 'doubleClick': return `Double-click: ${info.innerText?.slice(0, 40) || ''}`;
      case 'input':       return `Type into: ${info.placeholder || info.ariaLabel || info.tagName || ''}`;
      case 'select':      return `Select "${evt.selectedText || evt.value}" from dropdown`;
      case 'check':       return `${evt.checked ? 'Check' : 'Uncheck'}: ${info.innerText || ''}`;
      case 'keyPress':    return `Key: ${evt.ctrlKey ? 'Ctrl+' : ''}${evt.key}`;
      case 'scroll':      return `Scroll to (${evt.scrollX}, ${evt.scrollY})`;
      case 'formSubmit':  return `Submit form`;
      default:            return '';
    }
  }

  private _esc(s: string): string {
    return (s || '')
      .replace(/\\/g, '\\\\')
      .replace(/"/g,  '\\"')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r')
      .replace(/\t/g, '\\t');
  }
}
